// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"strconv"
	"time"
)

// refreshChoice is one entry in the auto-refresh selector.
type refreshChoice struct {
	Seconds int
	Label   string
}

// refreshChoices drives the selector. "off" is first, and so is what the
// browser selects with no explicit selected attribute — the default is to poll
// nothing at all, and refresh.js only departs from it if a previous choice was
// stored.
var refreshChoices = []refreshChoice{
	{0, "off"},
	{5, "5s"},
	{15, "15s"},
	{30, "30s"},
	{60, "1m"},
	{300, "5m"},
}

// The favicon is Scratchpad's: the same ▚ glyph in the same accent orange,
// inlined as a data URI so the binary has no asset dependencies.
const favicon = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Ctext y='13' font-size='14' fill='%23ffb454'%3E%E2%96%9A%3C/text%3E%3C/svg%3E"

// PageView is everything the shell needs; Services carries the grid itself.
type PageView struct {
	Hostname string
	Services ServicesView
}

func Page(v PageView) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>switchboard</title><!-- SafeURL: templ's sanitizer only trusts http/https/mailto/tel, and\n\t\t\t     would otherwise replace this inline data: URI with about:invalid. --><link rel=\"icon\" href=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 templ.SafeURL
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinURLErrs(templ.SafeURL(favicon))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/layout.templ`, Line: 46, Col: 49}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"><link rel=\"stylesheet\" href=\"/static/style.css\"><script src=\"/static/htmx.min.js\"></script><script src=\"/static/search.js\" defer></script><script src=\"/static/refresh.js\" defer></script></head><body><header class=\"flex flex-wrap items-baseline gap-4 px-8 pt-8 pb-4\"><h1 class=\"m-0 text-h1 tracking-[0.02em]\"><span class=\"text-accent\">▚ </span>switchboard</h1><p class=\"m-0 text-muted text-meta\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(v.Hostname)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/layout.templ`, Line: 57, Col: 52}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</p><label class=\"ml-auto flex items-center gap-2\"><span class=\"sr-only\">filter services</span> <input id=\"search\" type=\"search\" autocomplete=\"off\" spellcheck=\"false\" placeholder=\"filter…\" class=\"w-56 bg-surface border border-border rounded-card px-3 py-1 font-mono text-row text-text placeholder:text-muted outline-none focus:border-accent\"></label> <label class=\"flex items-center gap-2\"><span class=\"sr-only\">auto-refresh interval</span> <span class=\"relative flex items-center\"><select id=\"interval\" class=\"appearance-none bg-surface border border-border rounded-card pl-3 pr-7 py-1 font-mono text-row text-muted outline-none cursor-pointer hover:border-accent focus:border-accent\" title=\"auto-refresh interval\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, o := range refreshChoices {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<option value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.ResolveAttributeValue(strconv.Itoa(o.Seconds))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/layout.templ`, Line: 78, Col: 47}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(o.Label)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/layout.templ`, Line: 78, Col: 59}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</option>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</select> <span class=\"pointer-events-none absolute right-2 text-muted text-tag\">▾</span></span></label><!--\n\t\t\t\t\tWith auto-refresh off by default, this is the only way to update\n\t\t\t\t\tthe grid short of reloading the whole page.\n\t\t\t\t--><button id=\"refresh-now\" type=\"button\" class=\"refresh-now bg-surface border border-border rounded-card px-3 py-1 font-mono text-row text-muted cursor-pointer hover:border-accent hover:text-accent\" title=\"refresh now\" aria-label=\"refresh now\">↻</button></header><!--\n\t\t\t\tNothing here polls on its own. Auto-refresh defaults to off, and\n\t\t\t\twhen it is switched on the interval is driven from refresh.js\n\t\t\t\trather than a fixed hx-trigger. Discovery is lazy, so a page that\n\t\t\t\tis not asking is a process doing no work at all.\n\t\t\t--><main id=\"services\" class=\"px-8 pt-4 pb-12\" hx-get=\"/partials/services\" hx-trigger=\"sb:refresh\" hx-swap=\"innerHTML\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Services(v.Services).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</main></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func stamp(t time.Time) string {
	return t.Format("15:04:05")
}

var _ = templruntime.GeneratedTemplate
